### ISSUE TITLE
After exiting liquid my bash becomes unusable

### ISSUE THREAD

**Issue by sveri** [mogenslund/liquid#1]
I just tried 0.4 typed some stuff and then typed C-q to exit liquid. Afterwards I cannot use my bash anymore. No keytypes are recognized and it looks like this:

![liq](https://cloud.githubusercontent.com/assets/498370/20029469/095c594a-a34d-11e6-8937-7e2d164e4dea.png)

After trying some more I figured out I can type and commands will be evaluated, I just can not see what I typed.

I am using: GNU bash, Version 4.3.46(1)-release (x86_64-pc-linux-gnu) in mate.

**Comment by mogenslund** [comment]
Hi @sveri 
Thank you for letting me know and for testing my applicaiton. I knew the bug already. I have now described the problem on my readme page, so people will be aware. It is because I do not know how to reverse the changes I do to the terminal to make the program work correctly. If someone knows, please let me know.
Workaround: Type "reset" (blindly) and the press Enter to restore the terminal.

**Comment by mogenslund** [comment]
It should be fixed now in version 0.4.1.
