### ISSUE TITLE
Keybindings.

### ISSUE THREAD

**Issue by pieceofduke** [mogenslund/liquid#13]
Hello again. Managed to fire up your creation, already feeling the potential. Whoa.
The thing is, I use Colemak keyboard layout, so I want to redefine ALL the keys right away.
So I had to dive into the source code to see where those are defined. And those are hardcoded all over the different files.
Wouldn't it be better to extract them to edn config files?..

**Comment by mogenslund** [comment]
The mappings are defined for each "app", so that is why they are spread a bit. The most common app is textapp, which is for editing text files. All the bindings for that is defined in textapp.clj. There is a global keymapping, which is used if the app-level keybinding does not resolve.
I like the concept os being able to map keys directly to functions. If I had to use edn files, I would need another mapping from the values in the edn to the real functions. That would take away the power to map to an inline function.

I made a function in textapp to allow users to overwrite the keybindings. In the liana example it would look like:

```clojure
(ns liana.core
  (:require [dk.salza.liq.editor :as editor]
            [dk.salza.liq.apps.textapp :as textapp]
            [dk.salza.liq.core]))

(def newkeys
  {"k" editor/backward-line
   "h" editor/backward-char
   "j" editor/forward-line
   "l" editor/forward-char})

(defn -main
  [& args]
  (doseq [[k v] newkeys]
    (textapp/set-navigation-key k v))
  (apply dk.salza.liq.core/startup args)
  (dk.salza.liq.core/init-editor)
  (editor/add-snippet "I am Liana")
  
  (editor/updated))

(ns user
  (:require [dk.salza.liq.tools.cshell :refer :all]
            [dk.salza.additives.blob :refer :all]))
```

Notice that in practise there will not be many more lines than remapped keys, which would also be the case with edn file.

And if for some reason you want to call a custom inline function (like moving forward twice) it could look like:

```clojure
(textapp/set-navigation-key "l" #(do (forward-char) (forward-char)))
```

If you want a very customized app, you can take a copy of like textapp.clj. Call it like mynewtextapp.clj. Do the changes and redefine the editor to use it as default with:

```clojure
(editor/set-default-app mynewtextapp/run)
```

See https://github.com/mogenslund/liquid-vim/blob/master/src/dk/salza/liquid_vim/core.clj
(An example of a more vim-like rewrite.)

**Comment by pieceofduke** [comment]
This is awesome, thank.you

**Comment by mogenslund** [comment]
No more work needed.
