### ISSUE TITLE
Typeahead app opens only in the first main window

### ISSUE THREAD

**Issue by tom-adsfund** [mogenslund/liquid#22]
If I "split below", then C-space, the typeahead opens in the new window, but the action is done only in the previous window, leaving the typeahead open in the new window.

The typeahead should open non-prompt buffers in whichever window the typeahead is used in.

**Comment by mogenslund** [comment]
OMG! This probably makes it obvious that I do not use splitting windows much myself :-) Thank you!

I think it is an easy fix. The typeaheadapp finds the previous buffer and navigates back to that. If the buffer is already visible in some window, it will switch to that. Since typeaheadapp occupies the current window, Liquid will switch to the other one, where the buffer is also present after the splitting.

I just need to make a variant of switch-to-buffer that does not try to be clever and change window. I guess it will be a matter of copy/paste, remove some code and use the new function from typeaheadapp.

**Comment by mogenslund** [comment]
I have commitet a fix now and updated liq.jar
