### ISSUE TITLE
[question] ijkl or hjkl?

### ISSUE THREAD

**Issue by zeronumbers** [mogenslund/liquid#35]
in video https://drive.google.com/file/d/0B5Au3PxHCmgBM2MySHl4aUVWTEE/view
 you say ijkl is for movement 
however 
in cheatsheet http://salza.dk/liquid/cheatsheet.html
it is written that hjkl is for movement
so which one is right?

**Comment by mogenslund** [comment]
Hi zeronumbers

The cheatsheet is right. I changed the default keybindings at some point after the video, due to some kind of "pressure" from people who like vim keybindings. I did see the point, though. Having "known" keybindings makes it a lot easier for new people to adopt. My original keybindings were an attempt to "improve" vim keybindings to something I found more natural myself. But making others use it failed.

**Comment by mogenslund** [comment]
As explained above.
