### ISSUE TITLE
Text input does not work with composition input (e.g. Japanese IMEs)

### ISSUE THREAD

**Issue by iku000888** [mogenslund/liquid#4]
Not sure what can be done about it, but throwing it out there.

**Comment by mogenslund** [comment]
[ttyinput.txt](https://github.com/mogenslund/liquid/files/594233/ttyinput.txt)

I have attached a program (rename from ttyinput.txt to ttyinput.clj). If you execute that in a terminal with a command similar to this: 

```java -cp clojure-1.8.0.jar:. clojure.main -m ttyinput```

it will output "A:" and a number each time you press a keybination. This number is what I use for translating keys into keywords and into actions. Try to see what happens when you type your special characters and provide me some numbers and maybe screenshots of which character is expected, then I will see, if I can use that to come up with a general solution for handling characters.

**Comment by mogenslund** [comment]
Self insert was implemented to handle more cases.
